apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
stringData:
    config.toml: ENC[AES256_GCM,data:vPvfx56XGf+h7WKXOa2YgtLSw9xYZAiG0rFxxsielFlowTEUUm0wEsgcAxxPmPODTib01fcO6Fjx1gxMF2eLMiVpLIwlrmxdLzk5qFfXDPwuqA5f6TUek5Iv3+gJigGLnBf1mPJsQ48vMDvwxt1hW1X6hk4LNoRd3BfeHTSFijL/Lf65DOEZ3mgZUbTkz/J/tg4AgwkcSKpuyLhjW4g3HMJuy3mfuryO8kq/N9kxKBNzjHoAQdP01ol5HY8Ja1hUljn0j74m+enP18MTXFwNT46OiD41pkc9BTBJf0a1iUU7bjqLtwyqyyRpxNgrkprhmRNDnIWyRoKcPErzDnYCSROK5kI7dvbIdn+JDlfrFB6fGAtWmKTF6f7ss2NeWPrHVNrbig==,iv:nVc6u2GGIr7YRIeTtMlZ6GQoE+BJyEqLatS7len80Ro=,tag:b8mjkzYERyxIBDD7lEDzUw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Ynp6YnNRNmJKOGtBS0lz
            Mndyc09EMXNZd1VWYVZEbDV5bG1pekhVZDFVCmFLdnVhS3V5R05QY0FDd05VaUov
            Q0JXZnV5VndTcUg1MUNkcXJrcldpUVEKLS0tIHZESjkwRjIvRk1wODgzSDkyTjZS
            Snp3NkxCaDR6MWR0SDVrUVZRWXRrY28KKFXOwxcWE9aP5a41XZBj1PRKpE9YhtIk
            2GgpQJfszpe2ZBMXpn3qdNucvVJF2FQcAzlcHK+wChYf1yzK3+1bLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-28T02:33:09Z"
    mac: ENC[AES256_GCM,data:IWCtpmrdlCAlqtVfZO0xQ202GOqVVtkqxTp9TMrajKVE5HadEETd0uRmVYaCIxu4C128OE4PYNh1yG/6pcnnwv66AIiVsJpQ8aEImWi164xKPLv/pLOVor5Zv4gGbnfQMtPJyo/41V8R0RNX6X4iDtaH3HGXmI8U6LCltD6tGF4=,iv:xLH4WL4KtEEp4xMfILFmTTHzc1lW2qNI48b1tU5mED8=,tag:eq1Y7c4Q29+FHZbcos4yIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
