apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:MiaDdVbxKlUk,iv:vuHlJcPpK0+dlMqgbJYH66uJhG+9qPcqVtfEApCdf5w=,tag:T6Rvw89ULxF3tTcHqTqAfQ==,type:str]
    admin-user: ENC[AES256_GCM,data:Uf0ov2U=,iv:hKtOrrrldSJ9BSWu5zr3DyfBvAlBMe7XcmOxdyF9TPk=,tag:rVtDhrqzcLtsNI0q4PVQ9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMWJ6Z0Z1R0Q5VzlMTUtP
            dWoyOS9wRE1hQi92QkpFMFY1OVJycnBVM0M4CmFxUlNyN3Y1aU1SNlIrUzl6dW9p
            Yk4rNlVUMGxPbGhTTEYwSkVXaS9waWMKLS0tIFRPSm5HR3JhRjU3eW9TTXhFV21W
            REJiOHV0c2tUb09TcVNZK2RoYStlRDQK4gBJKVLNntYVqLYyouBEOEmdMt6zk03Z
            JYsn7imlUGuvs6HuiAjtNjQ7brh5UWGv2OGoQ758IuAzuNoNb7AXkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-28T02:33:03Z"
    mac: ENC[AES256_GCM,data:d5bBy5F1ZOfx24TxL5OzprB6rPJrvx5R+nSdtlfUE/eM04oiRwcILh2iv0aOeW+9GdU0XxNEkcRxgrP64C7fVYCSf+1dK8QqzNkiEfHf3UXTu5Ef+URslYCkJNbTBNV/oOt1VW3aqbkxrxJIBuIJNywrINkg2Y25KGCjyE4JZNc=,iv:gYsif374UlBlrgnSxC7m3JYxqcmgbYhF4od0jvIpmGE=,tag:gKfhtE9UuX/Yo9/wf9d9pw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
