apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:7BXvmnlgqHy1G7hRPgXAW4KWWJ1PK03a,iv:cHPTW3TiD/qE+mozcGI44VDZxFIm3juB7+jHvLL/jVA=,tag:Y23w+CWmlE8Y45uf8qLQSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VzZDem40VnJpMUY4azFw
            Z3pjSjVscitWeDYvMy82aWlqWURLZE15alZZCkY0bStBb1NSZUp6aEFraUhLOXFC
            YmhpTTRpYk1DTWxqNFR3bnR6dnN1RWsKLS0tIERYR0VrRzNYdDZ3ODlDcDJ0RWFW
            L3hSMkN3QmQ2Zk1DOFBPNCtuV0VCWTAKICnyiylww0vnc15NTwx+F9/ZBPKrC9zC
            soTE+ewqraaWZijGsKfXjLJ1G8THxqAYvNFJpeYTSdtYhqQriiJ3Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-28T03:36:26Z"
    mac: ENC[AES256_GCM,data:HcCvARNqBo20sAeV+fjp40ulsuBPhs/dwdcB8PICtD+2Byo+BxHOJSp1SKZp6gX79FfdY+XmjC/U0710sqpeYxqksUnIBt4BPDw9e2t43CScaBER+afQ4F0ntw3GZk9bxVyx1MKQm1+WX1vNLkLgdRAXKUrHL8M6uTHQ9gHhVXc=,iv:Qd1pOR2h7SzqjvORvWpaNixG5aDrNKxUWlheyoxZSBU=,tag:Kqjh7krmBIFqh+DySf3xjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
