apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:DDp+KJ584J3dL09dzfkKKQlIMQcMgkIdLK7nGxCNxCsM8KiqbY2IbQ==,iv:TjjV3TeARNtY4ybETNb67wR9I20ld9piN4s+63Bivv4=,tag:1doNTkGni22z2vHVxPnJFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZDIwZzJzTzgxUk54Smsz
            cmMxeEVvUXAxMnRSdnZtcXlqSmdlQi9kT2hzCnZlSHNCVVQ1RVRCQzUzNTMzSnh5
            ZUxHOXZVb0wxU2swVk1vSllZUEtrWE0KLS0tIGowZC9meDY0aTJrRlh0U0F5TDhT
            YStuTWxjalJWZnUwdklJbUFlRXBTNk0KU/gZZGneZnJR5bgvOXQyiBA0NYFZSr8H
            HFs1wd2GE3FeW+IUaEpZcdfDHQT0wJtvdPQU/EJlU3IxcgE8ZwY0/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-28T02:32:58Z"
    mac: ENC[AES256_GCM,data:Jtm64SaNkFiHbdzH46Ht0590jO+oP1c0TNeXBDox8GvJ0ffKrU19EU9oGlj6/69PuSzAB70iq8yjCprGTQnspe5toXSiD+rORM7Dy2WDiVCChZtxmQ63hM2ZK/33rfs2UOJm4nttKTshHlHoqrOpTNMJg8E3E7l6W6HpDVHxE8Q=,iv:QDty8Wd6fFgbbTHcMpHkqp0SL/p/CvtLi2v9YxKAXp0=,tag:QJkIHucgcq5IUuVpbPW/Yg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
