apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:R9ZZz7Cu8mAKCRUTcSL06EZmnni/S8kRl38nxMyT1gd1O64OUPfXyA==,iv:RiRCOLufqm5/m0fh9MW12yreOGIk1ttl9XaEfcCR6w0=,tag:zxqW3Lqdk5noaNN+SKiZMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRK2FBQlBZSjEzMzZNWFpH
            amtWN1VaK2xVK1lEeWl3OC9Jc1c3RWR3N1I0CmFvT3NrV2RGWkhqYlFqY05vSDQ2
            ZGVIaWtjYXpNU05sMFBaaksvQTdXTTAKLS0tIEdnZEhlcnNrYzVaUzlXOVluWnZi
            SVQ2TVBrdWRJSGFYdTRJVHdnb05KZXcKtgbG5zGjrfpDFXZEjXlP6BIQCcxwxFDy
            8JmKR6eVDjGY/XM6GunwwJzQIYZA4ERy7BocmAcnTvsvz2iNDi+4YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-17T20:26:43Z"
    mac: ENC[AES256_GCM,data:sHd14Uu4NHC2YY5ceZ9pRKaaF+F7EHJZGUpXTTvtoBWC/psDjoyV+X7qsSbMo7SEl3F1HcXK7XIe3xP1oYj1wB1lxXWxhuEbRquR5IvMyzgmDPpSF960i7wmWv08j1xIwP7QVvwa1rNKyvqjc+c5B6P3QtmTUO0p5Kbi/Q1SInk=,iv:cbiVpxRzHEWiPtmojtT6WQM6429mDkx64iVCuBfbPdU=,tag:tv8UP1pvwdKpq4QRiKQLAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
