apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:X8WBMogPHsY7D13l4uo4C1ltErpqJz8tjVYdA7dbfZAPkHrUxkAwVA==,iv:lCLHFynAr9/mebjeGnIVzCpJSHnGzQLVRYlp9UleTKU=,tag:gw4SVXiWDJyV3Lhg+7tqMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNkVSOVBGUHBadUxIa05j
            QzROMXhtRTQ0ZHFCb3IySWtPbjFKR0xjR3pvCmxCbHdXZXNaNmM3bDhuV1gvNURN
            cXhFMnhBQ0dkTnBxU3FTTVdEc1BFbE0KLS0tIC96a3BJUjJTcFNJYTYxUDc3ck1W
            WE1ZR2JINWFLazBUM29ZK0xsRzVjaFEK+ExFariSas3G2MmpTmfYfxY+FphbxrGI
            yS+mirjesjFcqMrliGKpRfjqj1NLsjhBNcZwgXL6cQu1zug+C/5HrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-19T21:42:08Z"
    mac: ENC[AES256_GCM,data:H/3hsPo6YRVjZNSXUf1crTIvBtbMT96XIZbfSt4zMh01u1vuVARe4dxBwP6So38cqrO7hHybWBxDXn06bEr1dSODwYWjRLYLQIidwI9agnoZK1tRcaurqcA6MI0xAFdiVQ2JxBlAIyjI4HXvsFfyJGnnTYWItQXV0nEFRDZ6svU=,iv:285+lgPeeKt6pkhfQNj+WOdFnTkVtz/8FPiEjk+P6ng=,tag:ZVXBXBEaYaba4ghFo1hdIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
