apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:UjnIzoT1YAhkyfjhksrXtSI8xOjLEstzHJF3Xm/VPX4abT6Gq9jifA==,iv:ph9iDroLuTmkpFfki7+cn2mSqQABUkC5eGgOTcTsA4g=,tag:eLi8J/qij71n5t8ZWb/Rvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUXU0VjBBOWhRRGh3K2RU
            emsyR2pJT3FJYWljdEFTQzNDT0F2ajRBR1RZCmVVR1F2VWRSZHBqSDdmYnMrUmoy
            WU9jWno4UU1JWWdwaVZQQmtPdnVMSWcKLS0tIFZCRjRLeHpTMTlmOXp1VERrTlo1
            K1BIdmVDSkl5TExvaVhCcEVtc0J4V3MKxQz555wQ1UfR/uTnhXztvwbJ/4gmccOb
            oZUmW8liBY65Z+hIGTHa3QgU2PG/7kj+SpsAnOJpUKV8pVm4U1qG0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-28T02:32:59Z"
    mac: ENC[AES256_GCM,data:zjNBfL0J346pqRtj79f8OkLOIQVCBIjw75Rlx7UHTIBtOB3hi3OJm8xkPKDw/m1NS7V8SNtxHRx7+b0yxMg114/pJypGTB0ULowO0T3aBdT+qUh7PS+b1VB26p5pMFvlEWNFGMfbbwRXxaLdJDjWxN0KShMqZQUkBC0ezmFVqB0=,iv:U3qkQEoOikKIe5nV4OhVr/Dayb30Ec9Exp42S/KS/gU=,tag:Nhh/BGnD9HX6I5sYYewEwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
