apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:/BbzBNzenabNhgdtjPdNTXj9k2yF0MPfQJktGoU0R2S1XUdhQG61jgGNO8kufIHRs6lwfXeSm1H9EyYh,iv:9uUjVR46fpAEf9aiAml2WKjVEBiSJPcc1w+jBlQdoc0=,tag:wR8CVSIH1gi1YT6MsJcIUQ==,type:str]
    username: ENC[AES256_GCM,data:bvSntZs=,iv:RQ0uty+vDlUlF4AdRHZsAGmEB2FrEvU9LKVPMBr4A5g=,tag:24HI2exwH2DBtPAovZVyGA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodTdSeEJ5YXMweCtYcnJq
            L2JaUTVBVklPN3lmQXN3eno2ZDBUWkUzQ0NnCkFHZGp4UVFOOWorbCtwdmprVFlz
            SUVjUCtZQUZ5eDgzNit5cGgxQ0lHUTAKLS0tIDZYd0krQ1crSzNvaGpqdlp1RjN2
            Tmh4RnJGbWtpaFpzanVuSUg5bVhsZ00K1JccH4vUR0wHEbsHmRLPs7Yb73ieJkHG
            Nc1tJC6sNPpVFvKpS4hH2AhVX/C1NliFAu3ktMxyGljasvrKjSbd1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-28T02:33:08Z"
    mac: ENC[AES256_GCM,data:4OG6XKJTMniPi3Mw2Bj0EqV/xt7mY46srGSsu3NPkcJEs+TuWpg+7abLnavIA76mdr6MDGz/sp2xQ+SVR+x4l7RujV5KHkU5bupKEqZvVpsvBOFLnjN+FF3cEbqZ0eeaZAlg+qOTRtyuLbOIKohAzd9F2rjSL+qRkB2YCSoWAZs=,iv:9duQzTbFHUn8dXpog1N5JqZSIlRQbrPfnsWFd2km1xo=,tag:7pYqoUNxh2aIeycl9QUCfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
