apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:cqXzZOh6r2ljZ3OHaA==,iv:6Wpll/CRrvcD1AxzIC8jD6wY2lBkMekS2d8FpXJAYCw=,tag:K2IaBleLb/9AAxvgb4evlg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:JWRGnRwETXfXO/jAi2tqaysT,iv:9sRgh9kEGYsweAi2lUGEH4MmqbtXejF+pVlgJMJZPSY=,tag:CSC7TBdX98yzms2Ah1hENg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Jo+8GH7eBkWbV8Mu/HUpwcPY3hU2mV60CzbbDfpT8cYTH5bN,iv:lllaKWZyVCXbb15A/7QsEww9hfKv91KxwgbD60iImBE=,tag:5an6pSJ/cq8FRZ0bTunt5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUFhIaWdKdTBQQWJiVjF0
            Tk95SU9MclZBQXpQZE9QM2ZqWWZpM0xGNTJVCnJ1d2llZlhrT05hWG9RazZYcVNn
            RHNTOVh5R3c2c3pwODNYVVc1U0pPOG8KLS0tIEQrUytNZGlPMzB0QXNKMWdhdkor
            YVB6NndUdnRUZVVMT1hENFZ3ODBxMVUKPE8Jcp1Aro1V4QwWqPDJi+GL77MxAmEA
            1/Amgr1Jiqg7lNKO3Uy9GDx1F/J7sSXCvg1su01SGGY7a9fCu0vLTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-19T21:42:08Z"
    mac: ENC[AES256_GCM,data:iMAss7ZDxMsAExxcNGksX/CbSJH+wIi/GIGPgOw3pMKZMzjb4DZNCR5L5aWRoNpAn1qXY8QO+M8X+H1yeO7B96rorkOLhTwVg3IZU4FyTkfzR+a0+iDtEayDZGjEFmg3mN8IxVQcN2ADKYIl/RqkWiUgoCdaoYY5JL+WyXxIjGo=,iv:bg9AK2IyorfTerMzUunrv6atyI7bAzvvvRrzwX8Z81M=,tag:ufGk0MkEnS31y5T59ufCYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
