apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:WryyZFOIGlL0eeXb,iv:07+cqqP7pre3LsJC+7lhJd/gNTW8BRrSN+WfhobMtPo=,tag:2ElBPWUOjntzhQkPGxlGnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTmZLUXZFOXllbFFYSm01
            K1lwaTQ1ZGdYMFdBS0wzK3lodWlSTlIydEJFCnArSGR1dEtuWGpjem1QNGlFQmN4
            Y2lkVms2Uis1SzVDcUpIeGlCeHR3NHcKLS0tIFdldEhuNlh2eFJPbGlHR0VoUGt0
            aEpBNlVISHpUNGExK2d4bEhDejY3M3MKgL/LmFAysOYtcAxGVThehT8+RofRz/3K
            kG6PZSN6iQZSms8xCQd+sdGZCnbxypbZtzmEb514e9SL2Dle/5YJIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-28T02:32:59Z"
    mac: ENC[AES256_GCM,data:U7cNJuXXaNPzaXGnUEylmCTpRFJHB/rfVDRTx/HIFEsJd8E81OU0P9p+fcKekoPXL1rsSpf6hNRGLF95KEWFKO2HPtQe33wC/Nu+fVVXO6JWH2vxJmKF4zUkuZuxI0GLOvZQQMySFau4bwlwuh5PLKy4sKYJUeBM4nYcOAfwHRo=,iv:zP3Rhrdh/ZHT12SecFVe/nQCuR+NA1qmxm8RoSMyz8I=,tag:rxaNzLm5oSdXiZE6jYIPew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
