apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:+6aO8ukON/tB/EObhusQrg==,iv:IdLsR/FlXsELu5MeEeUstX160KOs1Nqfi4U3mc/9Lkk=,tag:CTD8apJdby0VPMKXFbLiBg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:yyCRpkt6aJo7AN2/DUHJvMpTmQUj7T6b9nxh89Dc5gi75/zS,iv:T0eYDL+U64fu2j9/uf9DDTDjIZkII1OiUYjPYbnGb6k=,tag:aFZLoDZmExDhRvMUbisR6A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:qe5wmq/c548PG1Ow2Q==,iv:f6dHscQsMHnqQC/A2tru76+9iC5Sz2/u2mpKlZTeWnU=,tag:Ag0oDLfi+7QPG+jUo/tZrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ekoxZXF6L242S2trSWpQ
            V2JuaWhFd1gwQjIydmNJRHRxWlgxU3M3VGlJClFKZmpQVXdRSXZ6WFhBU0EyT1Av
            S1FMcHVlYTNNclJkMnZwNStsWUZKRUkKLS0tIDEyRGpmQnpCS1E2VmJ1ekJxV2Fz
            Z0NDeG9Xc2toRzVtQXFGMStqbCtKK1kKWwGiIxFGJYsSUmP6sgIs9Z7p+kYArV2r
            6hnXCDJKQ6OATPiYIIdoEUtq0nyRruNWpd/qTSTLojfPsfFgtWmhIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-28T02:33:00Z"
    mac: ENC[AES256_GCM,data:eDQldYDvd8Iiw6Yv3ymg0X9NseECDS4aauKSswR0yBXyD7bct8KeMD5FcjCFFHH+WhE5hprWH0EN+r1XS30S9juSO6g+UnFd9sWzZWy2ppqx7igekkg5ec4h8X1xldOKw0X1QGzIF7NqUNUOPg5JTT9cvwWKka2V4BJYArqh6xs=,iv:xmASg+Po15Bhf2W11j+/mUMtdOF1BBxIh2155lRi/Yo=,tag:zDFZjoncfv/EDs+Clmsh/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
