apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:GTMhL2piHbyCLFb9vX4mCx16RvfG4gToHdOwOm67t8GpvDHP,iv:z+erg81S+DlJESuB54iNIX6DUGf6pntT4oNzyf2iOAs=,tag:eG35Bm0ShmdD8ESOb7a5cw==,type:str]
    credentials.json: ENC[AES256_GCM,data:PLr03dQzksicfXVZOaw1d/frftODPXTa6VJk81EE9FdlR71zweTrWr2kAQ1hCV2wLUg5Ca7f4VuEY3PCv8JsebSZEpMmQqKnvNK/Hbw0UqH0V7xctUgl/bzoei3xAGkjmdeAifPlKo1L+Nok9MlHgNN8+hAwLmqdvFRBjLfHQO9MV95NHELTaSoXxinpHxoIE4mrDXrm0fq8YbbULQuTcMNHkWKxqv8NLPdTeg7uKA==,iv:HYFfBM/SS9XATtVR3XJBNmRtojfGqYHeRL0bNpPXBYw=,tag:Byap9l8arPlKs3sEVLEJIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYUZaV1hjaDU4ZFh5VjAx
            TGFqam84aG95U01SUHJVUWFZQkw0dk5JTFNBClNRNTN0TWs1VDBiZ2dEMnBRVTVt
            aVNVQlZpeDNIVHp4V1JYN0lwRHpIWlEKLS0tIGl2ZlpVRVVYRjhERm1pcitMR0ZX
            VDI5TTRuelgwekkvcWd2NzltRHMzVm8KAcCcO4ojWCAdOiK8iqLIyKnlwSp10HBD
            KzpjjwyhUbSiIKyEWsCXTdnCeBL2Ad8pvyLYUf6u9voIBILfeV8QkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-28T02:32:59Z"
    mac: ENC[AES256_GCM,data:PucXMozQmicrmNMa1vyR4moDZzYELmHWVoleHWwsuF5cC6FAF7/K/vTH0IoA5CuZspg7FkmGxWcvuA93OUIJTit3ntJzDGR6+yrOkvrtxEI3kjFfEYlgBeze7VEPB8nQq32t39+tE19omFUvW+54IxaKapUN3MpIaBMmssvAWLE=,iv:ueQ41SOPXtR9yvzxhyAyQv5lFH7G39iCHXP8D6Gq5f4=,tag:txzqLtLOEt1mCrYuvstDjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
