apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:D9TgGCqjp5s4kI+c6HOzTeBJ+Q6L9NP5CBCS1fXn0BY=,iv:HQS48gIfMP8Ku9u74mKD6cuAphO8gI/Lvxt55fezsbk=,tag:GwZBhzoVQ7oMMlfYV54BWw==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:LOpmENUOe7J75JZtFu33oUTwExBEprj/pSIGv53UU1S0S1GE,iv:j9TtOC7OD88HPi23L+1EJbWnVd9BXXF5dfz4p4AWPZY=,tag:pJPSjOJXYpkyyW8JZf8zsA==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:VKdSWYdqLbnQpUmJpHrx85A5IRrlukzxLxHBNJdGwvFGQrXo6js1cw==,iv:dJ+pqm0KJgZOKERUCagvIDw/Wc0jjoRqAayup7lH0Mw=,tag:o7OGZLQL5VicJLSzSj9L8w==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:39wSui0=,iv:TJXq/G92UzM1YuJsmBTtCGeDkTLk/ePtNkKSdusU0fQ=,tag:GTp7JUD9mKd4/SVGihHYuA==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:xJ59CLLxDHRj,iv:Ysw/u746d1iSlYJqe6aQ0NHryW1XeURYczciv8X+61w=,tag:evJeRCUA2HLOBaydllqQhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ec9knaw849tmq39ax3wuxke5w0dh3l2gzwc794n52uj0fnt4549qj4tmwt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsU1JkUFRadTh1OFkrbmg4
            UWNYcFRjZTJCQ1ZiU05iemhDMjgydEJHeGd3CkhnendWT3BzbU43UnY2YVNHNkkx
            dmZIb00rSXFFR3NtbnN0aU1MaUNmWTQKLS0tIHQwRFhWWnlsODduTnh1ZHBKSjN3
            N2VmNWdFeTFicnNNQ1FMcVJBNWhzbk0KrpzS5lrhfkoAH9hWiFNtHrriE/15IEno
            6Lptc31R7JKLRfnyYAyiC/w5s648E4NmPL5fUDxjZP3imHRAGXLpbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-17T20:26:43Z"
    mac: ENC[AES256_GCM,data:XRevt37KU4b/dgieFw3XPdv2hI55BWXftT3mIyZON20+CvfFs2tf11zpuU4VGKmcGA7GWPNig4dppx2KBVW7/L9abXSPA3fzG3S7otM6FEKjQdrUXHmAw7pHEXs5ki/hfORB7ACI5qYWeOW4m5pyGsrV/1qgOG+pu8UoZ0cIyzg=,iv:RzDJnSerYIWShCl1xOdfhxfZCfjrs98QugmPp7UbpQA=,tag:La/uIYKULxkY968ZmwUUxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
